###
GET http://localhost:3456/

###
POST http://localhost:3456/movies
Content-Type: application/json

{
    "title": "Knight fall",
    "year": 2012,
    "director": "Christopher Morty",
    "duration": 152,
    "poster": "https://i.ebayimg.com/images/g/yokAAOSw8w1YARbm/s-l1200.jpg",
    "genre": ["Action"],
    "rate": 9.2
}

###

GET http://localhost:3456/products/ghi789

###

GET http://localhost:3456/products?tag=ECO

###
GET http://localhost:3456/products

###

POST http://localhost:3456/products
Content-Type: application/json

{
    "name": "Re-usable bag",
    "price": 2.99,
    "category": "Gadgets",
    "inStock": true,
    "rating": 7.8,
    "tags": ["eco", "trending"]
}

###

PATCH http://localhost:3456/products/def456
Content-Type: application/json

{
    "inStock": true,
    "price": 20.99
}