#CREAMOS LA CLASE USER PARA REPRESENTAR A CADA USUARIO
class User
#CREAMOS EL MÉTODO CONSTRUCTOR PARA INICIALIZAR LOS ATRIBUTOS DE CADA INSTANCIA DE LA CLASE USER
    def __init__(self, username, password):
        self.username = username
        self.password = password
#CREAMOS EL MÉTODO PARA VALIDAR EL LOGIN
    def login (self, entered_username, entered_password):
# COMPARAMOS EL NOMBRE DE USUARIO Y LA CONTRASEÑA INGRESADOS CON LOS QUE SE ALMACENARON EN LA INSTANCIA
        if entered-username == entered_username and entered_password self, password:
            return True
        else:
            return False
# CREAMOS UN OBJETO DE LA CLASE USER CON UN NOMBRE DE USUARIO Y CONTRASEÑA ESPECÍFICOS
    user1 = USER("MIUSUARIO", "MIPASSWORD")
#SOLICITAMOS AL USUARIO QUE INGRESE SU NOMBRE DE USUARIO Y CONTRASEÑA
ENTERED_USERNAME INPUT("INGRESE SU NOMBRE DE USUARIO: ")
ENTERED_PASSWORD INPUT("INGRESE SU CONTRASEÑA: ")
# INTENTAMOS HACER LOGIN CON LOS DATOS INGRESADOS
IF USER.LOGIN (ENTERED_USERNAME, ENTERED_PASSWORD): PRINT(¡BIENVENIDO!)
ELSE:
PRINT("NOMBRE DE USUARIO O CONTRASEÑA INCORRECTOS.")